name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:  # For golangci-lint
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
{%- raw %}
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-v0-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-v0-

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-v0-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pre-commit-v0-

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install pre-commit
        uses: threeal/pipx-install-action@v1.0.0
        with:
          packages: pre-commit

      - name: Install goimports
        run: |
          go install golang.org/x/tools/cmd/goimports@latest

      - name: Setup Git Token Auth
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          echo "GOPRIVATE=github.com/RogueConsultingDev" >> $GITHUB_ENV
          git config --global "url.https://mathieu-lemay:${{ secrets.ACCESS_TOKEN }}@github.com/RogueConsultingDev/.insteadof" https://github.com/RogueConsultingDev/ \

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59

      - name: Run Linters
        run: make lint

      - name: Run Tests
        run: make test
{% endraw -%}

{%- if cookiecutter.project_type == "application" %}
{%- raw %}
      - name: Build image
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: make docker.build
{% endraw -%}
{% endif -%}
