name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:  # For golangci-lint
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-v0-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-v0-

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-v0-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pre-commit-v0-

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install pre-commit
        uses: threeal/pipx-install-action@v1.0.0
        with:
          packages: pre-commit

      - name: Install goimports
        run: |
          go install golang.org/x/tools/cmd/goimports@latest

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59

      - name: Run Linters
        run: make lint

      - name: Run Tests
        run: make test
