name: CI

on:
  push:
    branches: ["*"]

jobs:
  validate-template:
    runs-on: ubuntu-latest
    name: "Validate Project Template"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: threeal/pipx-install-action@v1.0.0
        with:
          packages: cruft pre-commit

      - name: Configure Git
        run: |
          git config --global user.name "CI User"
          git config --global user.email "ci@example.com"

      - name: Install Go Linters
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -  -b "$(go env GOPATH)/bin" v1.59.0
          echo "PATH=$(go env GOPATH)/bin:$PATH" >> $GITHUB_ENV

      - name: Test template
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make test
